### ISSUE TITLE
Ruby 3.0 対応

### ISSUE THREAD

**Issue by ima1zumi** [rurema/doctree#2458]
3.0 の変更点をまとめてチェックリストにしました。 叩き台として作ったので自由に編集してください。

builtin library はあまり見ていません。また、対応済のものがあるかどうかはほとんど確認していません。

作業が終わったらこちらの issue にリンク or コメントするか、直接この issue を編集していただけるとありがたいです 🙏 

## 言語の変更

- [ ] キーワード引数の分離 [Feature \#14183](https://bugs.ruby-lang.org/issues/14183)
- [ ] ブロックがキーワード引数を受け取る場合の意味の整理 [Feature \#16166](https://bugs.ruby-lang.org/issues/16166)
- [ ] 引数委譲の記法の拡張 [Feature \#16378](https://bugs.ruby-lang.org/issues/16378)
- [ ] パターンマッチが正式機能になった [Feature \#17260](https://bugs.ruby-lang.org/issues/17260)
- [ ] 右代入が導入された (EXPERIMENTAL) [Feature \#17260](https://bugs.ruby-lang.org/issues/17260) 
- [ ] 1行パターンマッチが再設計された (EXPERIMENTAL) [Feature \#17371](https://bugs.ruby-lang.org/issues/17371)
- [ ] findパターンが追加された (EXPERIMENTAL) [Feature \#16828](https://bugs.ruby-lang.org/issues/16828)
- [ ] 一行メソッド定義が追加された (EXPERIMENTAL) [Feature \#16746](https://bugs.ruby-lang.org/issues/16746)
- [ ] 式展開を含む文字列リテラルは、frozen-string-literal: true で freeze しなくなった [Feature \#17104](https://bugs.ruby-lang.org/issues/17104)
  - 書くことなさそう
- [ ] RBSの追加
- [ ] TypeProfの追加
- [ ] deprecated警告がデフォルトで出ないことになった [Feature \#16345](https://bugs.ruby-lang.org/issues/16345)
- [x] `$SAFE` と `$KCODE` の削除 [Feature \#16131](https://bugs.ruby-lang.org/issues/16131) [Feature \#17136](https://bugs.ruby-lang.org/issues/17136)
- [ ] シングルトンクラス定義の中での yield が禁止になった [Feature \#15575](https://bugs.ruby-lang.org/issues/15575)
  - 書くことなさそう
- [ ] スーパークラスでクラス変数を再定義してしまったとき、サブクラスで参照したときに例外が出るようになった [Bug \#14541](https://bugs.ruby-lang.org/issues/14541)
  - 書くことなさそう
- [ ] 番号指定パラメータへの代入が警告から禁止になった
  - まず番号指定パラメータ(Numbered Parameter)の記述がない

## コマンドラインオプション

- [ ] `--help` にページャーがついた [Feature \#16754](https://bugs.ruby-lang.org/issues/16754)
- [ ] `--backtrace-limit` オプション [Feature \#8661](https://bugs.ruby-lang.org/issues/8661)

## 組み込みライブラリ

- [ ] Array のサブクラスのメソッドが、サブクラスではなく、Array クラスのオブジェクトを返すようになった [Bug \#6087](https://bugs.ruby-lang.org/issues/6087)
- [ ] String のサブクラスのメソッドが、サブクラスではなく、String クラスのオブジェクトを返すようになった [Bug \#10845](https://bugs.ruby-lang.org/issues/10845)
- [ ] Modified `Binding#eval` `Kernel#eval` [Bug \#4352](https://bugs.ruby-lang.org/issues/4352) [Bug \#17419](https://bugs.ruby-lang.org/issues/17419)
  - 引数を受け取ったときの挙動が変更になった

- [ ] Modified `ConditionVariable#wait` [Feature \#16786](https://bugs.ruby-lang.org/issues/16786)
- [ ] Modified `Dir.glob` `Dir.[]` [Feature \#8709](https://bugs.ruby-lang.org/issues/8709)
  - デフォルトでソートされるようになった
- [ ] Add `ENV.except` [Feature \#15822](https://bugs.ruby-lang.org/issues/15822)
- [ ] Modified `ENV` [Feature \#12650](https://bugs.ruby-lang.org/issues/12650)
  - ロケールによらず `UTF-8` になった
- [ ] Add `IBM720` Encoding [Feature \#16233](https://bugs.ruby-lang.org/issues/16233)
- [ ] Windows 環境でのデフォルトの `Encoding.default_external` が `UTF-8` になった [Feature \#16604](https://bugs.ruby-lang.org/issues/16604)
- [ ] Fiber Scheduler が導入された
- [ ] Add `GC.auto_compact = true` [Feature \#17176](https://bugs.ruby-lang.org/issues/17176)
- [ ] Modified `Hash#transform_keys` and `Hash#transform_keys!` [Feature \#16274](https://bugs.ruby-lang.org/issues/16274)
- [ ] Add `Hash#except` [Feature \#15822](https://bugs.ruby-lang.org/issues/15822)
- [ ] Modified `IO#nonblock?` [Feature \#16786](https://bugs.ruby-lang.org/issues/16786)
  - デフォルトで `true` を返すようになった
- [ ] Modified `IO#wait_readable, IO#wait_writable, IO#read, IO#write and other related methods `[Feature \#16786](https://bugs.ruby-lang.org/issues/16786)
- [ ] Modified `Kernel#clone`
- [ ] Modified `Kernel#lambda`
- [ ] Modified `Kernel.sleep`
- [ ] Modified `Module#include and Module#prepend`
- [ ] Modified `Module#attr_accessor, Module#attr_reader, Module#attr_writer and Module#attr `[Feature \#17314](https://bugs.ruby-lang.org/issues/17314)
- [ ] Modified `Module#alias_method` [Feature \#17314](https://bugs.ruby-lang.org/issues/17314)

- [ ] Modified `Proc#== and Proc#eql?` [Feature \#14267](https://bugs.ruby-lang.org/issues/14267) 
- [ ] Modified `Queue#pop, SizedQueue#push` [Feature \#16786](https://bugs.ruby-lang.org/issues/16786)
- [ ] Add Ractor Class
- [ ] Modified `Random::DEFAULT`
- [ ] Modified `Symbol#to_proc`
  - lambda を返すようになった
- [ ] Add `Symbol#name`
  - frozen string literal を返す
- [ ] Add `Fiber.set_scheduler` `Fiber.scheduler` [Feature \#16786](https://bugs.ruby-lang.org/issues/16786)
- [ ] Add `Fiber.blocking?` [Feature \#16786](https://bugs.ruby-lang.org/issues/16786)
- [ ] Add `Thread#join` [Feature \#16786](https://bugs.ruby-lang.org/issues/16786)
- [ ] Add `Thread.ignore_deadlock` [Bug \#13768](https://bugs.ruby-lang.org/issues/13768)
- [ ] Modified `Warning#warn` [Feature \#17122](https://bugs.ruby-lang.org/issues/17122)

## 標準添付ライブラリ

[ruby/NEWS\.md at v3\_0\_0 · ruby/ruby](https://github.com/ruby/ruby/blob/v3_0_0/NEWS.md#stdlib-updates)

## 非互換

- [ ] `Regexp` と `Range` オブジェクトが freeze されるようになった [Feature \#8948](https://bugs.ruby-lang.org/issues/8948) [Feature \#16377](https://bugs.ruby-lang.org/issues/16377) [Feature \#15504](https://bugs.ruby-lang.org/issues/15504)
- [ ] `Hash#each` が常に2要素配列をyieldするようになった [Bug \#12706](https://bugs.ruby-lang.org/issues/12706)
  - 最適化のバグ修正。書くことないかも
- [ ] 標準出力がクローズされた後に出力しようとしてもEPIPE例外を投げないようになった [Bug \#14413](https://bugs.ruby-lang.org/issues/14413)
- [ ] 定数の `TRUE` と `FALSE` と `NIL` が定義されないようになった
  - `Object` クラス
- [ ] `Integer#zero?` が改めて定義された [Misc \#16961](https://bugs.ruby-lang.org/issues/16961)
  - 今までは `Numeric#zero?` を使っていた
- [ ] `Enumerable#grep` `Enumerable#grep_v` に正規表現を渡してブロックを渡さなかった場合、 `$~` を更新しなくなった [Bug \#17030](https://bugs.ruby-lang.org/issues/17030)
- [ ] open-uri が `Kernel#open` を上書き定義しなくなった [Misc \#15893](https://bugs.ruby-lang.org/issues/15893)
  - 今後は `URI.open` を使う
- [ ] `SortedSet` が削除された
  - 別の gem に分離された

## 標準添付ライブラリの非互換

[ruby/NEWS\.md at v3\_0\_0 · ruby/ruby](https://github.com/ruby/ruby/blob/v3_0_0/NEWS.md#stdlib-compatibility-issues)

## C API

[ruby/NEWS\.md at v3\_0\_0 · ruby/ruby](https://github.com/ruby/ruby/blob/v3_0_0/NEWS.md#c-api-updates)

## 静的解析

[ruby/NEWS\.md at v3\_0\_0 · ruby/ruby](https://github.com/ruby/ruby/blob/v3_0_0/NEWS.md#static-analysis)

## その他の変更点

[ruby/NEWS\.md at v3\_0\_0 · ruby/ruby](https://github.com/ruby/ruby/blob/v3_0_0/NEWS.md#miscellaneous-changes)

## ref
- [Ruby 3\.0\.0 リリース](https://www.ruby-lang.org/ja/news/2020/12/25/ruby-3-0-0-released/)
- [ruby/NEWS\.md at v3\_0\_0 · ruby/ruby](https://github.com/ruby/ruby/blob/v3_0_0/NEWS.md)
- [プロと読み解く Ruby 3\.0 NEWS \- クックパッド開発者ブログ](https://techlife.cookpad.com/entry/2020/12/25/155741)

**Comment by osyo-manga** [comment]
* `Module#alias_method` を対応した https://github.com/rurema/doctree/pull/2462

**Comment by osyo-manga** [comment]
> Modified Hash#transform_keys and Hash#transform_keys! Feature #16274
 
 これは既に対応されていそうです。
see: https://github.com/rurema/doctree/commit/a807a9292989837c8b606232aa260359825bb64a

**Comment by ima1zumi** [comment]
@osyo-manga 
ありがとうございます 😄 反映しました。

**Comment by osyo-manga** [comment]
以下修正済みです

* Modified Kernel#lambda
    * https://github.com/rurema/doctree/pull/2488

**Comment by ima1zumi** [comment]
@osyo-manga 
ありがとうございます。反映しました〜
